apiVersion: apps/v1
kind: Deployment
metadata:
  name: sort-array-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sort-array
  template:
    metadata:
      labels:
        app: sort-array
    spec:
      containers:
        - name: sort-array
          image: gcr.io/devops-final-430412/sort-array:latest
          ports:
            - containerPort: 3200
---
apiVersion: v1
kind: Service
metadata:
  name: sort-array-service
spec:
  selector:
    app: sort-array
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3200
  type: LoadBalancer
