name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run tests for frontend
        run: |
          cd frontend
          npm install
          npm audit
          npm test -- --forceExit

      - name: Install dependencies and run tests for is-prime
        run: |
          cd is-prime
          npm install
          npm audit
          npm test -- --forceExit

      - name: Install dependencies and run tests for sortArray
        run: |
          cd sortArray
          npm install
          npm audit
          npm test -- --forceExit

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Artifact Registry
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and push frontend Docker image
        run: |
          cd frontend
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest

      - name: Build and push is-prime Docker image
        run: |
          cd is-prime
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/is-prime:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/is-prime:latest

      - name: Build and push sortArray Docker image
        run: |
          cd sortArray
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sort-array:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sort-array:latest

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials my-cluster --zone us-central1-a
          kubectl apply -f k8s/deployment-frontend.yaml
          kubectl apply -f k8s/deployment-is-prime.yaml
          kubectl apply -f k8s/deployment-sort-array.yaml
name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run tests for frontend
        run: |
          cd frontend
          npm install
          npm audit
          npm test -- --forceExit

      - name: Install dependencies and run tests for is-prime
        run: |
          cd is-prime
          npm install
          npm audit
          npm test -- --forceExit

      - name: Install dependencies and run tests for sortArray
        run: |
          cd sortArray
          npm install
          npm audit
          npm test -- --forceExit

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Artifact Registry
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and push frontend Docker image
        run: |
          cd frontend
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest

      - name: Build and push is-prime Docker image
        run: |
          cd is-prime
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/is-prime:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/is-prime:latest

      - name: Build and push sortArray Docker image
        run: |
          cd sortArray
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sort-array:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sort-array:latest

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials my-cluster --zone us-central1-a
          kubectl apply -f k8s/deployment-frontend.yaml
          kubectl apply -f k8s/deployment-is-prime.yaml
          kubectl apply -f k8s/deployment-sort-array.yaml
