name: CI Pipeline

on:
  push:
    branches: ["*"] # This triggers the workflow on push to any branch
  pull_request:
    branches: ["*"] # This triggers the workflow on pull request to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests for frontend
        working-directory: ./frontend
        run: npm test

      - name: Run tests for isPrime
        working-directory: ./is-prime
        run: npm test

      - name: Run tests for sortArray
        working-directory: ./sortArray
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        run: |
          docker build -t ${DOCKER_USERNAME}/frontend:latest ./frontend
          docker push ${DOCKER_USERNAME}/frontend:latest

      - name: Build and push isPrime
        run: |
          docker build -t ${DOCKER_USERNAME}/is-prime:latest ./is-prime
          docker push ${DOCKER_USERNAME}/is-prime:latest

      - name: Build and push sortArray
        run: |
          docker build -t ${DOCKER_USERNAME}/sortArray:latest ./sortArray
          docker push ${DOCKER_USERNAME}/sortArray:latest
